import React from "react";
import "./TermsConditions.css";

const TermsConditions = () => {
  return (
    <div className="tc-wrapper">
      <div className="tc-header">
        <h1>Terms & Conditions</h1>
      </div>

      <div className="tc-container">

        <section className="tc-card">
          <h2>1. Legal Status of This Document</h2>
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules made thereunder, including amended
            provisions pertaining to electronic records. This electronic record
            is generated by a computer system and does not require any physical
            or digital signatures.
          </p>
        </section>

        <section className="tc-card">
          <h2>2. Platform Publication & Compliance</h2>
          <p>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries Guidelines)
            Rules, 2011, which require publishing the rules and regulations,
            privacy policy, and Terms of Use for access or usage of the domain
            name https://uniquedesignconsultant.in/ (Website), including its
            related mobile site and mobile application (collectively referred
            to as the “Platform”).
          </p>
        </section>

        <section className="tc-card">
          <h2>3. Platform Ownership</h2>
          <p>
            The Platform is owned by 8958847686, a company incorporated under the
            Companies Act, 1956, with its registered office at Rishikesh
            (hereinafter referred to as the Platform Owner,we us or our).
          </p>
        </section>

        <section className="tc-card">
          <h2>4. Applicability of Terms</h2>
          <p>
            Your use of the Platform, services, and tools is governed by these
            Terms of Use, including applicable policies incorporated by
            reference. By using the Platform, you enter into a binding
            agreement with the Platform Owner. Any additional or conflicting
            terms proposed by you are expressly rejected.
          </p>
        </section>

        <section className="tc-card">
          <h2>5. Modification of Terms</h2>
          <p>
            These Terms of Use may be modified at any time without assigning any
            reason. It is your responsibility to review the Terms periodically
            to stay informed of updates.
          </p>
        </section>

        <section className="tc-card">
          <h2>6. User Definition</h2>
          <p>
            For the purpose of these Terms, “you”, “your”, or “user” means any
            natural or legal person who has agreed to become a user or buyer on
            the Platform.
          </p>
        </section>

        <section className="tc-card">
          <h2>7. Acceptance of Terms</h2>
          <p>
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR
            AGREEMENT TO ALL THE TERMS AND CONDITIONS contained herein. Please
            read the Terms carefully before proceeding.
          </p>
        </section>

        <section className="tc-card">
          <h2>8. User Information & Account Responsibility</h2>
          <p>
            To access and use the Services, you agree to provide true, accurate,
            and complete information during and after registration. You shall
            be responsible for all acts carried out through your registered
            account on the Platform.
          </p>
        </section>

        <section className="tc-card">
          <h2>9. Disclaimer of Warranties</h2>
          <p>
            Neither the Platform Owner nor any third party provides any warranty
            or guarantee regarding the accuracy, timeliness, performance,
            completeness, or suitability of the information and materials
            offered on the Platform or through the Services. Liability for
            inaccuracies or errors is expressly excluded to the fullest extent
            permitted by law.
          </p>
        </section>

        <section className="tc-card">
          <h2>10. Use at Your Own Risk</h2>
          <p>
            Your use of the Platform and Services is entirely at your own risk
            and discretion. You are required to independently ensure that the
            Services meet your requirements.
          </p>
        </section>

        <section className="tc-card">
          <h2>11. Intellectual Property</h2>
          <p>
            All content on the Platform, including design, layout, look, and
            graphics, is proprietary and licensed to the Platform Owner. You do
            not have any authority to claim intellectual property rights, title,
            or interest in the content.
          </p>
        </section>

        <section className="tc-card">
          <h2>12. Unauthorized Use</h2>
          <p>
            Unauthorized use of the Platform and/or Services may lead to action
            under these Terms of Use and applicable laws.
          </p>
        </section>

        <section className="tc-card">
          <h2>13. Payment Obligation</h2>
          <p>
            You agree to pay the charges associated with availing the Services.
          </p>
        </section>

        <section className="tc-card">
          <h2>14. Lawful Use</h2>
          <p>
            You agree not to use the Platform and/or Services for any unlawful,
            illegal, or prohibited purpose under these Terms or applicable
            Indian or local laws.
          </p>
        </section>

        <section className="tc-card">
          <h2>15. Third-Party Links</h2>
          <p>
            The Platform and Services may contain links to third-party websites.
            Accessing such links will be governed by the respective third-party
            terms, privacy policies, and other policies. These links are
            provided for convenience and additional information only.
          </p>
        </section>

        <section className="tc-card">
          <h2>16. Transaction Binding</h2>
          <p>
            Upon initiating a transaction for availing Services, you enter into
            a legally binding and enforceable contract with the Platform Owner.
          </p>
        </section>

        <section className="tc-card">
          <h2>17. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless the Platform Owner,
            affiliates, group companies, officers, directors, agents, and
            employees from any claim, demand, action, or penalty arising due to
            your breach of these Terms, Privacy Policy, other policies,
            violation of law, or infringement of third-party rights.
          </p>
        </section>

        <section className="tc-card">
          <h2>18. Force Majeure</h2>
          <p>
            Neither party shall be liable for failure or delay in performance if
            such failure is caused by a force majeure event.
          </p>
        </section>

        <section className="tc-card">
          <h2>19. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of India.
          </p>
        </section>

        <section className="tc-card">
          <h2>20. Jurisdiction</h2>
          <p>
            All disputes arising out of or in connection with these Terms shall
            be subject to the exclusive jurisdiction of the courts in India.
          </p>
        </section>

        <section className="tc-card">
          <h2>21. Communication</h2>
          <p>
            All concerns or communications relating to these Terms must be
            communicated using the contact information provided on the
            Platform.
          </p>
        </section>

        <section className="tc-card">
          <h2>Refund and Cancellation Policy</h2>

          <h2>1. Policy Scope</h2>
          <p>
            This policy outlines the process for cancellation and refunds for
            products or services purchased through the Platform.
          </p>

          <h2>2. Cancellation Requests</h2>
          <p>
            Cancellation requests will only be considered if made within 7 days
            of placing the order. Cancellation may not be entertained if the
            order has been communicated to sellers or merchants and the
            shipping or delivery process has been initiated. In such cases,
            products may be rejected at the time of delivery.
          </p>

          <h2>3. Perishable Items</h2>
          <p>
            Cancellation requests are not accepted for perishable items such as
            flowers or eatables. Refund or replacement may be provided if the
            user establishes that the quality of the delivered product is not
            satisfactory.
          </p>

          <h2>4. Damaged or Defective Products</h2>
          <p>
            In case of damaged or defective products, the issue must be
            reported to customer service within 7 days of receipt. The request
            will be entertained after verification by the seller or merchant.
          </p>

          <h2>5. Product Not as Expected</h2>
          <p>
            If the product received is not as shown on the Platform or does not
            meet expectations, the issue must be reported within 7 days of
            delivery. The customer service team will review and take an
            appropriate decision.
          </p>

          <h2>6. Manufacturer Warranty</h2>
          <p>
            For products covered under a manufacturer’s warranty, complaints
            must be directed to the respective manufacturer.
          </p>

          <h2>7. Refund Processing</h2>
          <p>
            In case of approved refunds, it may take up to 30 days for the
            refund to be processed.
          </p>
        </section>

      </div>
    </div>
  );
};

export default TermsConditions;
